/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author wadad
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Monitores = new javax.swing.JMenu();
        GestionMonitores = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Socios = new javax.swing.JMenu();
        GestionSocios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();
        SalirAplicacion = new javax.swing.JMenuItem();
        Volver_Atras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión del Gimnasio \"Body Perfect\"");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        Monitores.setText("Monitores");

        GestionMonitores.setText("Gestion de Monitores");
        GestionMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionMonitoresActionPerformed(evt);
            }
        });
        Monitores.add(GestionMonitores);

        jMenuItem2.setText("Cuota de Monitor");
        Monitores.add(jMenuItem2);

        jMenuBar1.add(Monitores);

        Socios.setText("Socios");

        GestionSocios.setText("Gestion de Socios");
        Socios.add(GestionSocios);

        jMenuBar1.add(Socios);

        jMenu3.setText("Actividades");
        jMenuBar1.add(jMenu3);

        Salir.setText("Salir");

        SalirAplicacion.setText("Salir de la aplicación");
        Salir.add(SalirAplicacion);

        Volver_Atras.setText("Volver Atras");
        Salir.add(Volver_Atras);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionMonitoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionMonitoresActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem GestionMonitores;
    public javax.swing.JMenuItem GestionSocios;
    public javax.swing.JMenu Monitores;
    public javax.swing.JPanel PanelPrincipal;
    public javax.swing.JMenu Salir;
    public javax.swing.JMenuItem SalirAplicacion;
    public javax.swing.JMenu Socios;
    public javax.swing.JMenuItem Volver_Atras;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
